server:
  port: 8080

spring:
  application:
    name: MicroservicioInicial

eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



