
server:
  port: ${PORT:8888}

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cytelsystem/BackEndII
          default-label: ServidorCentralizadoConfiguracion
          search-paths: Cajero
